"""
draw_line_to_closest_dot tool.
Auto-generated by the agent.
"""

from typing import List
from langchain.tools import Tool


import cv2
import numpy as np

def draw_line_to_closest_dot(input_image_path, output_image_path):
    # Load the image
    image = cv2.imread(input_image_path)
    
    # Convert the image to HSV color space
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
    
    # Define the color range for detecting the green circle
    green_lower = np.array([30, 50, 50])
    green_upper = np.array([90, 255, 255])
    
    # Define the color range for detecting the gold dots
    gold_lower = np.array([20, 100, 100])
    gold_upper = np.array([30, 255, 255])

    # Create masks for green and gold
    green_mask = cv2.inRange(hsv, green_lower, green_upper)
    gold_mask = cv2.inRange(hsv, gold_lower, gold_upper)

    # Find contours for green circle and gold dots
    green_contours, _ = cv2.findContours(green_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    gold_contours, _ = cv2.findContours(gold_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

    # Find the center of the green circle
    if green_contours:
        green_cnt = max(green_contours, key=cv2.contourArea)
        (x_green, y_green), radius_green = cv2.minEnclosingCircle(green_cnt)
        center_green = (int(x_green), int(y_green))
    else:
        raise ValueError("No green circle found in the image.")

    # Initialize variables to find the closest gold dot
    min_distance = float('inf')
    closest_center = None

    # Find the closest gold dot
    for contour in gold_contours:
        (x_gold, y_gold), radius_gold = cv2.minEnclosingCircle(contour)
        center_gold = (int(x_gold), int(y_gold))
        distance = np.linalg.norm(np.array(center_green) - np.array(center_gold))

        if distance < min_distance:
            min_distance = distance
            closest_center = center_gold

    # Draw a line from the center of the green circle to the closest gold dot
    if closest_center:
        cv2.line(image, center_green, closest_center, (255, 0, 0), 5)
        cv2.imwrite(output_image_path, image)
    else:
        raise ValueError("No gold dot found in the image.")



def create_image_processing_tools() -> List[Tool]:
    """Create and return the draw_line_to_closest_dot tool."""
    return [
        Tool(
            name="draw_line_to_closest_dot",
            func=draw_line_to_closest_dot,
            description="Draws a blue line from a green circle to the closest gold dot in an image using CV2.. Input: Input image path and output image path.",
        ),
    ]
