"""
Tool writing tools.
Allows the agent to create new tools dynamically.
"""

import os
import re
from pathlib import Path
from typing import List

from langchain_compat import BaseModel, Field, StructuredTool, Tool


# Tools directory
TOOLS_DIR = Path(__file__).parent


class WriteToolInput(BaseModel):
    """Input for write_tool tool."""
    tool_file_name: str = Field(
        description="Name for the tool file (e.g., 'weather_tools' - .py will be added automatically)"
    )
    tool_name: str = Field(
        description="Name of the tool as it will appear to the agent (e.g., 'get_weather')"
    )
    tool_description: str = Field(
        description="Description of what the tool does, for the agent to understand when to use it"
    )
    function_implementation: str = Field(
        description="Complete Python function implementation (the actual code that does the work)"
    )
    requires_input: bool = Field(
        default=True,
        description="Whether the tool takes input parameters (True) or is parameter-less (False)"
    )
    input_description: str = Field(
        default="",
        description="Description of the input parameter if requires_input is True"
    )


def write_tool(
    tool_file_name: str,
    tool_name: str,
    tool_description: str,
    function_implementation: str,
    requires_input: bool = True,
    input_description: str = ""
) -> str:
    """
    Write a new tool to a Python file and update __init__.py to load it automatically.
    
    Args:
        tool_file_name: Name for the tool file (without .py extension)
        tool_name: Name of the tool for the agent
        tool_description: Description of what the tool does
        function_implementation: The Python function code
        requires_input: Whether the tool takes an input parameter
        input_description: Description of the input (if requires_input is True)
        
    Returns:
        Success or error message
    """
    try:
        # Clean up file name
        tool_file_name = tool_file_name.strip()
        if tool_file_name.endswith('.py'):
            tool_file_name = tool_file_name[:-3]
        
        # Security: prevent path traversal
        if '..' in tool_file_name or '/' in tool_file_name or '\\' in tool_file_name:
            return "Error: Invalid tool file name. Name cannot contain path separators or '..'."
        
        # Ensure it's a valid Python module name
        if not re.match(r'^[a-z][a-z0-9_]*$', tool_file_name):
            return "Error: Tool file name must be a valid Python module name (lowercase, alphanumeric and underscores, starting with letter)."
        
        tool_file_path = TOOLS_DIR / f"{tool_file_name}.py"
        
        # Check if file already exists
        if tool_file_path.exists():
            return f"Error: Tool file '{tool_file_name}.py' already exists. Choose a different name or delete the existing file first."
        
        # Extract function name from implementation
        func_match = re.search(r'def\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*\(', function_implementation)
        if not func_match:
            return "Error: Could not find a function definition in the implementation. Make sure it starts with 'def function_name('."
        
        function_name = func_match.group(1)
        
        # Generate the tool file content
        if requires_input:
            tool_content = f'''"""
{tool_name} tool.
Auto-generated by the agent.
"""

from typing import List
from langchain_compat import Tool


{function_implementation}


def create_{tool_file_name}() -> List[Tool]:
    """Create and return the {tool_name} tool."""
    return [
        Tool(
            name="{tool_name}",
            func={function_name},
            description="{tool_description}. Input: {input_description}",
        ),
    ]
'''
        else:
            tool_content = f'''"""
{tool_name} tool.
Auto-generated by the agent.
"""

from typing import List
from langchain_compat import Tool


{function_implementation}


def create_{tool_file_name}() -> List[Tool]:
    """Create and return the {tool_name} tool."""
    return [
        Tool(
            name="{tool_name}",
            func={function_name},
            description="{tool_description}",
        ),
    ]
'''
        
        # Write the tool file
        with open(tool_file_path, 'w', encoding='utf-8') as f:
            f.write(tool_content)
        
        # Update __init__.py to import and use the new tool
        init_path = TOOLS_DIR / "__init__.py"
        with open(init_path, 'r', encoding='utf-8') as f:
            init_content = f.read()
        
        # Add import statement after other tool imports
        import_line = f"from tools.{tool_file_name} import create_{tool_file_name}"
        
        # Find the last "from tools." import line and add after it
        import_pattern = r'(from tools\.[a-z_]+ import [^\n]+\n)'
        matches = list(re.finditer(import_pattern, init_content))
        if matches:
            last_import = matches[-1]
            insert_pos = last_import.end()
            init_content = init_content[:insert_pos] + import_line + '\n' + init_content[insert_pos:]
        else:
            return "Error: Could not find import section in __init__.py"
        
        # Add tool creation call in create_tools() function
        # Insert in the CUSTOM TOOLS SECTION
        tool_call_line = f"    # Add custom tool: {tool_name}\n    tools.extend(create_{tool_file_name}())\n    \n"
        
        # Insert in the custom tools section
        pattern = r'(\s+# === CUSTOM TOOLS SECTION.*===\n)'
        match = re.search(pattern, init_content)
        if match:
            insert_pos = match.end()
            init_content = init_content[:insert_pos] + tool_call_line + init_content[insert_pos:]
        else:
            return "Error: Could not find CUSTOM TOOLS SECTION in create_tools() function"
        
        # Write updated __init__.py
        with open(init_path, 'w', encoding='utf-8') as f:
            f.write(init_content)
        
        return (f"Successfully created new tool '{tool_name}'!\n"
                f"- Tool file: tools/{tool_file_name}.py\n"
                f"- Function: {function_name}\n"
                f"- Updated: tools/__init__.py\n\n"
                f"The tool will be available in the NEXT session (after restart). "
                f"Use the 'restart_conversation' tool to reload with the new tool.")
    
    except Exception as e:
        return f"Error writing tool: {str(e)}"


def create_tool_writing_tools() -> List[Tool]:
    """Create and return tool writing tools."""
    return [
        StructuredTool(
            name="write_tool",
            func=write_tool,
            description=(
                "Create a new tool that will be available to the agent in future sessions. "
                "This allows you to extend your own capabilities by writing new tools. "
                "Provide: tool_file_name (module name), tool_name (tool identifier), "
                "tool_description (what it does), function_implementation (Python code), "
                "requires_input (True/False), and input_description (if applicable). "
                "After creating a tool, use restart_conversation to reload with the new tool. "
                "Example: Create a tool to fetch weather data, perform calculations, or interact with APIs."
            ),
            args_schema=WriteToolInput,
        ),
    ]

